name=TKWifiManager
version=1.0.2
author=TehnoKraft (Oleg)
maintainer=TehnoKraft
sentence=AP+Captive Wi-Fi manager with OTA, FS manager, UDP discovery, and extensible routes for ESP32.
paragraph=Provides AP+Captive portal with live Wi-Fi scan, connects to best known networks, OTA update page, FS browser/uploader/editor, UDP broadcast discovery replies, and easy custom routes.
category=Communication
url=https://github.com/Jkl88/TKWifiManager
architectures=esp32
includes=TKWifiManager.h
